### ISSUE TITLE
Conductor crash

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercury#285]
[2021-12-17T09:09:02Z INFO  rocket::rocket] Matched: POST /swap/second application/json (swap_second_message)
[2021-12-17T09:09:02Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T09:09:02Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T09:09:02Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T09:09:02Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
[2021-12-17T09:09:02Z INFO  server_lib::protocol::conductor] SCHEDULER: Swap ID: aefa88a1-765a-42f4-ad71-fc8fd725f326 moved on to Phase3
[2021-12-17T09:09:02Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T09:09:02Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T09:09:03Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T09:09:03Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T09:09:03Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T09:09:03Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T09:09:03Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T09:09:03Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T09:09:03Z INFO  server_lib::protocol::conductor] SCHEDULER: Swap ID: aefa88a1-765a-42f4-ad71-fc8fd725f326 moved on to Phase3
[2021-12-17T09:09:03Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T09:09:03Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T09:09:04Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T09:09:04Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPublicKey', shared/src/state_chain.rs:263:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-12-17T09:09:04Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T09:09:04Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T09:09:04Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T09:09:04Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T09:09:05Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T09:09:05Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T09:09:05Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T09:09:05Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)

**Comment by tomt1664** [comment]
[2021-12-17T16:56:34Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:34Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:34Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:34Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:34Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPublicKey', shared/src/state_chain.rs:263:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-12-17T16:56:34Z INFO  rocket::rocket] POST /swap/poll/utxo application/json:
[2021-12-17T16:56:34Z INFO  rocket::rocket] Matched: POST /swap/poll/utxo application/json (poll_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:34Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T16:56:34Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:35Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T16:56:35Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:36Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:36Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:36Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:36Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:37Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:37Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:37Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:37Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:37Z INFO  rocket::rocket] POST /swap/poll/utxo application/json:
[2021-12-17T16:56:37Z INFO  rocket::rocket] Matched: POST /swap/poll/utxo application/json (poll_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:37Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T16:56:37Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:38Z INFO  rocket::rocket] POST /swap/poll/utxo application/json:
[2021-12-17T16:56:38Z INFO  rocket::rocket] Matched: POST /swap/poll/utxo application/json (poll_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:38Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T16:56:38Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:38Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:38Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:38Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:38Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:39Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:39Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:39Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:39Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:39Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:39Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:39Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:39Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:39Z INFO  rocket::rocket] GET /metrics application/openmetrics-text; version=0.0.1:
[2021-12-17T16:56:39Z INFO  rocket::rocket] Matched: GET /metrics
[2021-12-17T16:56:39Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:39Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:40Z INFO  rocket::rocket] POST /swap/poll/utxo application/json:
[2021-12-17T16:56:40Z INFO  rocket::rocket] Matched: POST /swap/poll/utxo application/json (poll_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:40Z INFO  rocket::rocket] GET /ping application/json:
[2021-12-17T16:56:40Z INFO  rocket::rocket] Matched: GET /ping (ping)
[2021-12-17T16:56:40Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:40Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:40Z INFO  rocket::rocket] GET /ping application/json:
[2021-12-17T16:56:40Z INFO  rocket::rocket] Matched: GET /ping (ping)
[2021-12-17T16:56:40Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:40Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:41Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:41Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:41Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:41Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:42Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:42Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:42Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:42Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:42Z INFO  rocket::rocket] POST /swap/poll/utxo application/json:
[2021-12-17T16:56:42Z INFO  rocket::rocket] Matched: POST /swap/poll/utxo application/json (poll_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:43Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:43Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:43Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:43Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:43Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:43Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:43Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:43Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:45Z INFO  rocket::rocket] POST /swap/poll/utxo application/json:
[2021-12-17T16:56:45Z INFO  rocket::rocket] Matched: POST /swap/poll/utxo application/json (poll_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T16:56:46Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T16:56:46Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T16:56:46Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:46Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:48Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:48Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:48Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:48Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:49Z INFO  rocket::rocket] GET /metrics application/openmetrics-text; version=0.0.1:
[2021-12-17T16:56:49Z INFO  rocket::rocket] Matched: GET /metrics
[2021-12-17T16:56:49Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:49Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:50Z INFO  rocket::rocket] GET /ping application/json:
[2021-12-17T16:56:50Z INFO  rocket::rocket] Matched: GET /ping (ping)
[2021-12-17T16:56:50Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:50Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:50Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:50Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:50Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:50Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:51Z INFO  rocket::rocket] GET /ping application/json:
[2021-12-17T16:56:51Z INFO  rocket::rocket] Matched: GET /ping (ping)
[2021-12-17T16:56:51Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:51Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:52Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:52Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:52Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:52Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:53Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:53Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:53Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:53Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:57Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:57Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:57Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:57Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:57Z INFO  rocket::rocket] POST /swap/deregister-utxo application/json:
[2021-12-17T16:56:57Z INFO  rocket::rocket] Matched: POST /swap/deregister-utxo application/json (deregister_utxo)
[2021-12-17T16:56:57Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:57Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T16:56:59Z INFO  rocket::rocket] GET /metrics application/openmetrics-text; version=0.0.1:
[2021-12-17T16:56:59Z INFO  rocket::rocket] Matched: GET /metrics
[2021-12-17T16:56:59Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T16:56:59Z INFO  rocket::rocket] Response succeeded.

**Comment by tomt1664** [comment]
[2021-12-17T17:44:34Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T17:44:34Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T17:44:34Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T17:44:35Z INFO  rocket::rocket] POST /swap/poll/swap application/json:
[2021-12-17T17:44:35Z INFO  rocket::rocket] Matched: POST /swap/poll/swap application/json (poll_swap)
[2021-12-17T17:44:35Z INFO  server_lib::protocol::conductor] SCHEDULER: Swap ID: bd9d1732-666f-45ff-970c-1d96f7d1092d moved on to Phase3
[2021-12-17T17:44:35Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T17:44:35Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T17:44:35Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T17:44:35Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPublicKey', shared/src/state_chain.rs:263:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-12-17T17:44:35Z INFO  rocket::rocket] POST /swap/poll/utxo application/json:
[2021-12-17T17:44:35Z INFO  rocket::rocket] Matched: POST /swap/poll/utxo application/json (poll_utxo)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T17:44:35Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T17:44:35Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T17:44:36Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T17:44:36Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T17:44:36Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T17:44:36Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T17:44:37Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T17:44:37Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T17:44:37Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T17:44:37Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T17:44:39Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T17:44:39Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T17:44:39Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T17:44:39Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T17:44:39Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T17:44:39Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/protocol/conductor.rs:839:88
[2021-12-17T17:44:40Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T17:44:40Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
[2021-12-17T17:44:40Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T17:44:40Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T17:44:40Z INFO  rocket::rocket] GET /metrics application/openmetrics-text; version=0.0.1:
[2021-12-17T17:44:40Z INFO  rocket::rocket] Matched: GET /metrics
[2021-12-17T17:44:40Z INFO  rocket::rocket] GET /swap/groupinfo application/json:
[2021-12-17T17:44:40Z INFO  rocket::rocket] Matched: GET /swap/groupinfo application/json (get_group_info)
thread '<unnamed>[2021-12-17T17:44:40Z INFO  rocket::rocket] Outcome: Success
[2021-12-17T17:44:40Z INFO  rocket::rocket] Response succeeded.
[2021-12-17T17:44:40Z INFO  rocket::rocket] POST /swap/register-utxo application/json:
[2021-12-17T17:44:40Z INFO  rocket::rocket] Matched: POST /swap/register-utxo application/json (register_utxo)
