### ISSUE TITLE
Tests failing: key_gen_and_sign, authentication_test_expired_token 

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/mercury#9]
Output of  "cargo test" is below.

```
running 9 tests
test auth::cognito::tests::get_user_id_test ... ok
test auth::jwt::tests::decode_token_test ... ok
test storage::mock::tests::quick_tests ... ok
test auth::jwt::tests::get_claims_test ... ok
(took PT0.007932S) test tests::tests::key_gen_and_sign ... FAILED
test tests::tests::authentication_test_expired_token ... FAILED
test tests::tests::authentication_test_invalid_token ... ok
test util::tests::sign ... ok
test util::tests::transaction ... ok

failures:

---- tests::tests::key_gen_and_sign stdout ----
thread 'tests::tests::key_gen_and_sign' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "IO error: lock : ./db/LOCK: No locks available" }', server/src/server.rs:148:28

---- tests::tests::authentication_test_expired_token stdout ----
thread 'tests::tests::authentication_test_expired_token' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "IO error: lock : ./db/LOCK: No locks available" }', server/src/server.rs:148:28


failures:
    tests::tests::authentication_test_expired_token
    tests::tests::key_gen_and_sign

test result: FAILED. 7 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p server --lib'
```

**Comment by tomossomot** [comment]
Did you run with 
`RUST_TEST_THREADS=1 cargo test --release` ?
